permissions:
- role: ADMIN
  privileges:
  - ADMIN
  - FOLDER_READ
  - FOLDER_CREATE
  - FOLDER_DELETE
  - DASHBOARD_READ
  - DASHBOARD_EDIT
  - DASHBOARD_DELETE
  - FILES_CREATE
  - FILES_READ
  - FILES_DELETE
  - MENU_UPDATE
  - MENU_DELETE
- role: ANONYMOUS
  privileges:
  - DASHBOARD_READ
- role: SYSTEM
  privileges:
  - ADMIN
