version: "3"
services:
  
  db:
    image: postgres:12
    container_name: sprout_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=sprout
      - POSTGRES_PASSWORD=sprout
      - POSTGRES_USER=sprout